version: "3"
services:
  mysql-spring:
    image: mysql:${MYSQL_VERSION:-latest}
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    container_name: mysql_spring

  spring:
    build:
      context: ./
    depends_on:
      - mysql-spring
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=mysql-spring
      - DATABASE_USER=root1
      - DATABASE_PASSWORD=Pikena_87
      - DATABASE_NAME=meaty
      - DATABASE_PORT=3306
    container_name: spring
volumes:
    data:
